networks:
  poop-cleaner:
    name: poop-cleaner-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24

services:
  redis:
    image: redis:7-alpine
    container_name: poop-cleaner-redis
    environment:
      PUID: 1000 # default user id
      PGID: 1000 # default group id
    command: redis-server
    volumes:
      - ./data/redis:/data
    networks:
      poop-cleaner:
        ipv4_address: 172.27.0.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  poop-cleaner:
    image: ghcr.io/derogab/poop-cleaner:latest
    container_name: poop-cleaner
    env_file:
      - ../.env
      - ./.env
    environment:
      PUID: 1000 # default user id
      PGID: 1000 # default group id
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      poop-cleaner:
        ipv4_address: 172.27.0.3
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - homepage.group=Bots
      - homepage.name=Poop Cleaner
      - homepage.icon=https://raw.githubusercontent.com/derogab/poop-cleaner/master/.github/assets/logo.png
      - homepage.href=https://github.com/derogab/poop-cleaner
      - homepage.description=Telegram bot that cleans spam from group chats
