name: summarygram

networks:
  summarygram:
    name: summarygram-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24

services:
  summarygram:
    image: ghcr.io/derogab/summarygram:latest
    container_name: summarygram
    env_file:
      - ../.env
      - ./.env
    environment:
      PUID: 1000 # default user id
      PGID: 1000 # default group id
      SQLITE_PATH: /data/summarygram.sqlite
    volumes:
      - ./models:/usr/src/app/models
      - ./data:/data
    networks:
      summarygram:
        ipv4_address: 172.26.0.3
    restart: unless-stopped
    labels:
      - homepage.group=Bots
      - homepage.name=SummaryGram
      - homepage.icon=https://raw.githubusercontent.com/derogab/summarygram/master/.github/assets/logo.png
      - homepage.href=https://github.com/derogab/summarygram
      - homepage.description=Telegram bot that summarizes group chats
